name: NuitkaBuilder

on:
  push:
    tags: [v*]
    branches: ["master", "main"]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional tag name (defaults to branch name)'
        required: false

permissions:
  contents: read

jobs:
  docker:
    timeout-minutes: ${{ matrix.host == 'qemu' && 30 || 10 }}
    strategy:
      matrix:
        host: ['amd', 'arm', 'qemu']
        type: ['glibc.', 'musl.', '']
    env:
      platforms: >-
        ${{ matrix.host == 'amd' && 'linux/386,linux/amd64' ||
            matrix.host == 'arm' && 'linux/arm/v6,linux/arm/v7,linux/arm64/v8' ||
            'linux/ppc64le,linux/riscv64,linux/s390x' }}
    environment:
      name: preview
      url: https://github.com/NewFuture/DDNS/pkgs/container/nuitka-builder/
    runs-on: ubuntu-${{ matrix.host == 'arm' && '24.04-arm' || 'latest' }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
        if: matrix.host == 'qemu'
        with:
          platforms: ${{ env.platforms }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ matrix.type }}Dockerfile
          platforms: ${{ env.platforms }}
          target: base-builder
          push: true
          tags: |
            ghcr.io/newfuture/nuitka-builder:${{ matrix.type }}${{ matrix.host }}

  preview-docker:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [docker]
    strategy:
      matrix:
        type: ['glibc', 'musl', '']
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: preview
      url: https://github.com/NewFuture/DDNS/pkgs/container/nuitka-builder/
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Merge images
        run: |
          set -ex
          # Determine tag name
          TAG_NAME="${{matrix.type}}${{matrix.type && '-'}}${{ github.event.inputs.tag || github.ref_name }}"
          suffix=
          docker buildx imagetools create \
            --tag ghcr.io/newfuture/nuitka-builder:$TAG_NAME \
            ghcr.io/newfuture/nuitka-builder:${{matrix.type}}.amd \
            ghcr.io/newfuture/nuitka-builder:${{matrix.type}}.arm \
            ghcr.io/newfuture/nuitka-builder:${{matrix.type}}.qemu
